export const FETCH_USERS_SUCCESS: string = "FETCH_USER_SUCCESS";
export const FETCH_USER_POSTS_SUCCESS: string = "FETCH_USER_POSTS_SUCCESS";
export const DELETE_USER_POST_SUCCESS: string = "DELETE_USER_POST_SUCCESS";
export const FETCH_USER_SUCCESS: string = "FETCH_USER_SUCCESS"